### ISSUE TITLE
get rid of get field `data`

### ISSUE THREAD

**Issue by gradso** [LeonasAnony/Kontaktformular#11]
Could we maybe get ride of the get field `data`?
I think it looks a bit ugly. Just my taste. I think get is nice for stuff like languages. We could use instead of it something like this:
```
    $data = $POST['data']
    if(emtpy($data)){
        $data=false;
    }
    .....
    <input type="hidden" name="data" value="true"> 
```

**Comment by LeonasAnony** [comment]
I think we don´t need data at all. It was just an old habit of me to send the form with a true variable assigned to it - absolut bullshit.
`if ($_SERVER["REQUEST_METHOD"] == "POST")` is way cleaner...
